### PR TITLE
Upgraded to work with Polymer 1.0.

### PR DESCRIPTION
**Pull request by lauyuen**
Signed-off-by: Yuen Lau hi@yuen-lau.com

### CODE REVIEW

**Comment by chadliu23** [comment]
Thanks I will update demo and page later

**Comment by chadliu23** [comment]
Thanks a lot

**Comment by lauyuen** [comment]
Thank you for making it in the first place. I've actually updated the integer demo and index page to work with Polymer 1.0 as well if that's what you're talking about. :+1:

**Comment by chadliu23** [comment]
Thanks for your update. I move around the files for polymer 1.0 developing tools 
following rules in https://www.polymer-project.org/1.0/docs/start/reusableelements.html

**Comment by chadliu23** [comment]
I also release v0.0.4. Thanks for your work.

**Pull request merged**
